/* generated by tools/gen_coeffs.py - do not edit by hand. */
#ifndef AMPNEVE_COEFFS_H
#define AMPNEVE_COEFFS_H

#define AMPNEVE_COEFFS_FS 44100.0f
typedef struct { float b0, b1, b2, a1, a2; } AmpBiquad;

/* cab DARK chain (TONE=0): woody 1x12, tighter/papery */
static const AmpBiquad AMP_CAB_DARK[] = {
    /* hp95 */ { 0.990474817f, -1.980949635f, 0.990474817f, -1.980858904f, 0.981040366f },
    /* body220 +3dB */ { 1.005368313f, -1.973004561f, 0.968605874f, -1.973004561f, 0.973974186f },
    /* midcut550 -2dB */ { 0.992738726f, -1.923468954f, 0.936650963f, -1.923468954f, 0.929389690f },
    /* pres4200 +4.5dB */ { 1.112010214f, -1.379800370f, 0.557967537f, -1.379800370f, 0.669977751f },
    /* lp9500 4th #0 */ { 0.058872744f, 0.117745487f, 0.058872744f, -0.226658571f, 0.051437586f },
    /* lp9500 4th #1 */ { 1.000000000f, 2.000000000f, 1.000000000f, -0.313856551f, 0.455936891f },
};
#define AMP_CAB_DARK_N 5

/* cab BRIGHT chain (TONE=1): glassier cone edge */
static const AmpBiquad AMP_CAB_BRIGHT[] = {
    /* hp95 */ { 0.990474817f, -1.980949635f, 0.990474817f, -1.980858904f, 0.981040366f },
    /* body220 +3dB */ { 1.005368313f, -1.973004561f, 0.968605874f, -1.973004561f, 0.973974186f },
    /* midcut550 -2dB */ { 0.992738726f, -1.923468954f, 0.936650963f, -1.923468954f, 0.929389690f },
    /* pres5500 +6dB */ { 1.184218003f, -1.154500435f, 0.445592149f, -1.154500435f, 0.629810152f },
    /* lp12000 4th #0 */ { 0.122702625f, 0.245405250f, 0.122702625f, 0.144615230f, 0.044397458f },
    /* lp12000 4th #1 */ { 1.000000000f, 2.000000000f, 1.000000000f, 0.200823666f, 0.450329449f },
};
#define AMP_CAB_BRIGHT_N 5

/* mic pickup (SM57-ish, fixed after cab) */
static const AmpBiquad AMP_MIC[] = {
    /* hp70 */ { 0.992972613f, -1.985945226f, 0.992972613f, -1.985895841f, 0.985994611f },
    /* pres5800 +3dB */ { 1.097481591f, -1.034904517f, 0.429923404f, -1.034904517f, 0.527404995f },
    /* lp11000 2nd */ { 0.291850733f, 0.583701465f, 0.291850733f, -0.004173023f, 0.171575954f },
};
#define AMP_MIC_N 3

/* neve EMO (VOICE=1): less HF sheen */
static const AmpBiquad AMP_NEVE_EMO[] = {
    /* lf shelf 110 +1.5dB */ { 1.000957615f, -1.978752231f, 0.978059573f, -1.978773243f, 0.978996177f },
    /* mid 700 +1dB */ { 1.007677054f, -1.864852542f, 0.866488639f, -1.864852542f, 0.874165693f },
    /* hf shelf 12k +0.5dB */ { 1.026791013f, 0.150040464f, 0.180047862f, 0.179598652f, 0.177280686f },
};
#define AMP_NEVE_EMO_N 3

/* cab DARK EMO (VOICE=1): woody, mid-forward, warmer top */
static const AmpBiquad AMP_CAB_DARK_EMO[] = {
    /* hp95 */ { 0.990474817f, -1.980949635f, 0.990474817f, -1.980858904f, 0.981040366f },
    /* body220 +3dB */ { 1.005368313f, -1.973004561f, 0.968605874f, -1.973004561f, 0.973974186f },
    /* body500 +1.5dB */ { 1.005959083f, -1.931862069f, 0.930815321f, -1.931862069f, 0.936774404f },
    /* pres3800 +4dB */ { 1.091757298f, -1.445082541f, 0.594485253f, -1.445082541f, 0.686242551f },
    /* lp9000 4th #0 */ { 0.049651072f, 0.099302144f, 0.049651072f, -0.301774992f, 0.060617691f },
    /* lp9000 4th #1 */ { 1.000000000f, 2.000000000f, 1.000000000f, -0.416321019f, 0.463200895f },
};
#define AMP_CAB_DARK_EMO_N 5

/* cab BRIGHT EMO (VOICE=1): glassier cone edge */
static const AmpBiquad AMP_CAB_BRIGHT_EMO[] = {
    /* hp95 */ { 0.990474817f, -1.980949635f, 0.990474817f, -1.980858904f, 0.981040366f },
    /* body220 +3dB */ { 1.005368313f, -1.973004561f, 0.968605874f, -1.973004561f, 0.973974186f },
    /* body500 +1.5dB */ { 1.005959083f, -1.931862069f, 0.930815321f, -1.931862069f, 0.936774404f },
    /* pres4800 +5dB */ { 1.137909366f, -1.275548445f, 0.507695121f, -1.275548445f, 0.645604486f },
    /* lp11000 4th #0 */ { 0.093312993f, 0.186625986f, 0.093312993f, -0.003702830f, 0.039569297f },
    /* lp11000 4th #1 */ { 1.000000000f, 2.000000000f, 1.000000000f, -0.005152148f, 0.446465232f },
};
#define AMP_CAB_BRIGHT_EMO_N 5

/* mic EMO (VOICE=1): a touch less bite, warmer */
static const AmpBiquad AMP_MIC_EMO[] = {
    /* hp70 */ { 0.992972613f, -1.985945226f, 0.992972613f, -1.985895841f, 0.985994611f },
    /* pres5500 +2dB */ { 1.061955521f, -1.077735643f, 0.459485647f, -1.077735643f, 0.521441169f },
    /* lp10000 2nd */ { 0.251379994f, 0.502759988f, 0.251379994f, -0.171241390f, 0.176761366f },
};
#define AMP_MIC_EMO_N 3

/* speaker resonance (fixed) */
static const AmpBiquad AMP_RESO_LOW = { 1.001790561f, -1.989040100f, 0.987472135f, -1.989040100f, 0.989262695f };
static const AmpBiquad AMP_RESO_HIGH = { 1.030435203f, -1.549983287f, 0.734476220f, -1.549983287f, 0.764911423f };

/* neve 1073-style tone (fixed brand color) */
static const AmpBiquad AMP_NEVE[] = {
    /* lf shelf 110 +1.5dB */ { 1.000957615f, -1.978752231f, 0.978059573f, -1.978773243f, 0.978996177f },
    /* mid 700 +1dB */ { 1.007677054f, -1.864852542f, 0.866488639f, -1.864852542f, 0.874165693f },
    /* hf shelf 12k +1.5dB */ { 1.082547122f, 0.121853144f, 0.188161348f, 0.212960162f, 0.179601452f },
};
#define AMP_NEVE_N 3

/* tone network runtime constants (linear gain A, no pow at runtime) */
#define AMP_TONE_BASS_F0 140.0f
#define AMP_TONE_BASS_COSW 0.999801073f
#define AMP_TONE_BASS_SINW 0.019945297f
#define AMP_TONE_BASS_ALPHA 0.011080721f
#define AMP_TONE_MID_F0 850.0f
#define AMP_TONE_MID_COSW 0.992675811f
#define AMP_TONE_MID_SINW 0.120808670f
#define AMP_TONE_MID_ALPHA 0.086291907f
#define AMP_TONE_TREB_F0 5000.0f
#define AMP_TONE_TREB_COSW 0.756808832f
#define AMP_TONE_TREB_SINW 0.653636284f
#define AMP_TONE_TREB_ALPHA 0.408522678f
#define AMP_TONE_TREB_HIGH 1

#endif
