/* generated by tools/gen_coeffs.py - do not edit by hand. */
#ifndef AMPNEVE_COEFFS_H
#define AMPNEVE_COEFFS_H

#define AMPNEVE_COEFFS_FS 44100.0f
typedef struct { float b0, b1, b2, a1, a2; } AmpBiquad;

/* cab DARK chain (TONE=0) */
static const AmpBiquad AMP_CAB_DARK[] = {
    /* hp90 */ { 0.990973873f, -1.981947747f, 0.990973873f, -1.981866274f, 0.982029219f },
    /* body180 +3dB */ { 1.004402908f, -1.978003864f, 0.974251601f, -1.978003864f, 0.978654509f },
    /* pres3200 +2.5dB */ { 1.045721389f, -1.549542080f, 0.680104994f, -1.549542080f, 0.725826383f },
    /* lp7000 4th #0 */ { 0.022290296f, 0.044580592f, 0.022290296f, -0.610947054f, 0.126073654f },
    /* lp7000 4th #1 */ { 1.000000000f, 2.000000000f, 1.000000000f, -0.821129085f, 0.513472932f },
};
#define AMP_CAB_DARK_N 4

/* cab BRIGHT chain (TONE=1) */
static const AmpBiquad AMP_CAB_BRIGHT[] = {
    /* hp90 */ { 0.990973873f, -1.981947747f, 0.990973873f, -1.981866274f, 0.982029219f },
    /* body180 +3dB */ { 1.004402908f, -1.978003864f, 0.974251601f, -1.978003864f, 0.978654509f },
    /* pres3200 +5dB */ { 1.094120751f, -1.578547131f, 0.664010454f, -1.578547131f, 0.758131206f },
    /* lp9000 4th #0 */ { 0.049651072f, 0.099302144f, 0.049651072f, -0.301774992f, 0.060617691f },
    /* lp9000 4th #1 */ { 1.000000000f, 2.000000000f, 1.000000000f, -0.416321019f, 0.463200895f },
};
#define AMP_CAB_BRIGHT_N 4

/* speaker resonance (fixed) */
static const AmpBiquad AMP_RESO_LOW = { 1.002307559f, -1.991886554f, 0.989801908f, -1.991886554f, 0.992109467f };
static const AmpBiquad AMP_RESO_HIGH = { 1.037707915f, -1.595895800f, 0.779482472f, -1.595895800f, 0.817190386f };

/* neve 1073-style tone (fixed brand color) */
static const AmpBiquad AMP_NEVE[] = {
    /* lf shelf 110 +2.5dB */ { 1.001597417f, -1.979340318f, 0.978023643f, -1.979375426f, 0.979585952f },
    /* mid 700 +1.5dB */ { 1.011544138f, -1.868187422f, 0.865973089f, -1.868187422f, 0.877517227f },
    /* hf shelf 12k +1dB */ { 1.054300169f, 0.136377579f, 0.184009450f, 0.196294617f, 0.178392582f },
};
#define AMP_NEVE_N 3

/* tone network runtime constants (linear gain A, no pow at runtime) */
#define AMP_TONE_BASS_F0 250.0f
#define AMP_TONE_BASS_COSW 0.999365712f
#define AMP_TONE_BASS_SINW 0.035611433f
#define AMP_TONE_BASS_ALPHA 0.017805717f
#define AMP_TONE_MID_F0 700.0f
#define AMP_TONE_MID_COSW 0.995030775f
#define AMP_TONE_MID_SINW 0.099567847f
#define AMP_TONE_MID_ALPHA 0.062229904f
#define AMP_TONE_TREB_F0 3000.0f
#define AMP_TONE_TREB_COSW 0.910035111f
#define AMP_TONE_TREB_SINW 0.414531177f
#define AMP_TONE_TREB_ALPHA 0.207265588f
#define AMP_TONE_TREB_HIGH 1

#endif
