/* generated by tools/gen_coeffs.py - do not edit by hand. */
#ifndef AMPNEVE_COEFFS_H
#define AMPNEVE_COEFFS_H

#define AMPNEVE_COEFFS_FS 44100.0f
typedef struct { float b0, b1, b2, a1, a2; } AmpBiquad;

/* cab DARK chain (TONE=0) */
static const AmpBiquad AMP_CAB_DARK[] = {
    /* hp90 */ { 0.990973873f, -1.981947747f, 0.990973873f, -1.981866274f, 0.982029219f },
    /* body180 +1.5dB */ { 1.002191164f, -1.976101835f, 0.974560690f, -1.976101835f, 0.976751853f },
    /* pres3200 +1.5dB */ { 1.027151803f, -1.537056716f, 0.684768813f, -1.537056716f, 0.711920616f },
    /* lp10000 4th #0 */ { 0.069175294f, 0.138350588f, 0.069175294f, -0.152054103f, 0.044907388f },
    /* lp10000 4th #1 */ { 1.000000000f, 2.000000000f, 1.000000000f, -0.211110064f, 0.450736685f },
};
#define AMP_CAB_DARK_N 5

/* cab BRIGHT chain (TONE=1) */
static const AmpBiquad AMP_CAB_BRIGHT[] = {
    /* hp90 */ { 0.990973873f, -1.981947747f, 0.990973873f, -1.981866274f, 0.982029219f },
    /* body180 +1.5dB */ { 1.002191164f, -1.976101835f, 0.974560690f, -1.976101835f, 0.976751853f },
    /* pres3200 +3dB */ { 1.055163473f, -1.555592453f, 0.677401607f, -1.555592453f, 0.732565080f },
    /* lp12000 4th #0 */ { 0.122702625f, 0.245405250f, 0.122702625f, 0.144615230f, 0.044397458f },
    /* lp12000 4th #1 */ { 1.000000000f, 2.000000000f, 1.000000000f, 0.200823666f, 0.450329449f },
};
#define AMP_CAB_BRIGHT_N 5

/* speaker resonance (fixed) */
static const AmpBiquad AMP_RESO_LOW = { 1.001790561f, -1.989040100f, 0.987472135f, -1.989040100f, 0.989262695f };
static const AmpBiquad AMP_RESO_HIGH = { 1.030435203f, -1.549983287f, 0.734476220f, -1.549983287f, 0.764911423f };

/* neve 1073-style tone (fixed brand color) */
static const AmpBiquad AMP_NEVE[] = {
    /* lf shelf 110 +2.5dB */ { 1.000957615f, -1.978752231f, 0.978059573f, -1.978773243f, 0.978996177f },
    /* mid 700 +1.5dB */ { 1.007677054f, -1.864852542f, 0.866488639f, -1.864852542f, 0.874165693f },
    /* hf shelf 12k +1dB */ { 1.082547122f, 0.121853144f, 0.188161348f, 0.212960162f, 0.179601452f },
};
#define AMP_NEVE_N 3

/* tone network runtime constants (linear gain A, no pow at runtime) */
#define AMP_TONE_BASS_F0 140.0f
#define AMP_TONE_BASS_COSW 0.999801073f
#define AMP_TONE_BASS_SINW 0.019945297f
#define AMP_TONE_BASS_ALPHA 0.011080721f
#define AMP_TONE_MID_F0 850.0f
#define AMP_TONE_MID_COSW 0.992675811f
#define AMP_TONE_MID_SINW 0.120808670f
#define AMP_TONE_MID_ALPHA 0.086291907f
#define AMP_TONE_TREB_F0 5000.0f
#define AMP_TONE_TREB_COSW 0.756808832f
#define AMP_TONE_TREB_SINW 0.653636284f
#define AMP_TONE_TREB_ALPHA 0.408522678f
#define AMP_TONE_TREB_HIGH 1

#endif
