import numpy as np, os, sys
sys.stdout.reconfigure(encoding='utf-8')
FS = 44100.0
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', 'core', 'ampsim_coeffs.h'))

def peaking(fs, f0, q, gain_db):
    A = 10.0 ** (gain_db / 40.0)
    w0 = 2.0 * np.pi * f0 / fs
    alpha = np.sin(w0) / (2.0 * q)
    b0 = 1.0 + alpha * A; b1 = -2.0 * np.cos(w0); b2 = 1.0 - alpha * A
    a0 = 1.0 + alpha / A; a1 = -2.0 * np.cos(w0); a2 = 1.0 - alpha / A
    return np.array([b0/a0, b1/a0, b2/a0, a1/a0, a2/a0])

def shelf(fs, f0, gain_db, high):
    A = 10.0 ** (gain_db / 40.0)
    w0 = 2.0 * np.pi * f0 / fs
    alpha = np.sin(w0) * np.sqrt(2.0) / 2.0
    c = np.cos(w0); sA = 2.0 * np.sqrt(A) * alpha
    if not high:
        b0 = A * ((A+1.0) - (A-1.0)*c + sA); b1 = 2.0*A*((A-1.0) - (A+1.0)*c); b2 = A*((A+1.0) - (A-1.0)*c - sA)
        a0 = (A+1.0) + (A-1.0)*c + sA; a1 = -2.0*((A-1.0) + (A+1.0)*c); a2 = (A+1.0) + (A-1.0)*c - sA
    else:
        b0 = A * ((A+1.0) + (A-1.0)*c + sA); b1 = -2.0*A*((A-1.0) + (A+1.0)*c); b2 = A*((A+1.0) + (A-1.0)*c - sA)
        a0 = (A+1.0) - (A-1.0)*c + sA; a1 = 2.0*((A-1.0) - (A+1.0)*c); a2 = (A+1.0) - (A-1.0)*c - sA
    return np.array([b0/a0, b1/a0, b2/a0, a1/a0, a2/a0])

def butter(fs, fc, order, kind):
    from scipy import signal
    sos = signal.butter(order, fc, kind, fs=fs, output='sos')
    return [np.array([b0/a0, b1/a0, b2/a0, a1/a0, a2/a0]) for b0,b1,b2,a0,a1,a2 in sos]

def fmt(name, arr, indent='    '):
    s = ', '.join(f'{v:.9f}f' for v in arr)
    return f'{indent}/* {name} */ {{ {s} }},\n'

C = []
C.append('/* generated by tools/gen_coeffs.py - do not edit by hand. */\n')
C.append('#ifndef AMPNEVE_COEFFS_H\n#define AMPNEVE_COEFFS_H\n\n')
C.append('#define AMPNEVE_COEFFS_FS 44100.0f\n')
C.append('typedef struct { float b0, b1, b2, a1, a2; } AmpBiquad;\n\n')

# --- cab DARK (TONE=0): HP90 + body180(+1.5) + pres3200(Q1.2,+1.5) + LP10000(4th)
#     Nashville session voice: tight lows, no honk, glassy top. ---
hp90 = butter(FS, 90.0, 2, 'highpass')[0]
body = peaking(FS, 180.0, 1.0, 1.5)
pres_dark = peaking(FS, 3200.0, 1.2, 1.5)
lp_dark = butter(FS, 10000.0, 4, 'lowpass')
C.append('/* cab DARK chain (TONE=0) */\n')
C.append('static const AmpBiquad AMP_CAB_DARK[] = {\n')
C.append(fmt('hp90', hp90)); C.append(fmt('body180 +1.5dB', body)); C.append(fmt('pres3200 +1.5dB', pres_dark))
for i,b in enumerate(lp_dark): C.append(fmt(f'lp10000 4th #{i}', b))
C.append('};\n#define AMP_CAB_DARK_N 5\n\n')

pres_bright = peaking(FS, 3200.0, 1.2, 3.0)
lp_bright = butter(FS, 12000.0, 4, 'lowpass')
C.append('/* cab BRIGHT chain (TONE=1) */\n')
C.append('static const AmpBiquad AMP_CAB_BRIGHT[] = {\n')
C.append(fmt('hp90', hp90)); C.append(fmt('body180 +1.5dB', body)); C.append(fmt('pres3200 +3dB', pres_bright))
for i,b in enumerate(lp_bright): C.append(fmt(f'lp12000 4th #{i}', b))
C.append('};\n#define AMP_CAB_BRIGHT_N 5\n\n')

# --- speaker resonance: 105Hz +2.5dB Q1.2, 3.5kHz +2dB Q1.6 (fixed)
#     Nashville: tighter lows, less cone ring. ---
reso_low = peaking(FS, 105.0, 1.2, 2.5)
reso_hi = peaking(FS, 3500.0, 1.6, 2.0)
C.append('/* speaker resonance (fixed) */\n')
C.append('static const AmpBiquad AMP_RESO_LOW = ')
C.append('{ ' + ', '.join(f'{v:.9f}f' for v in reso_low) + ' };\n')
C.append('static const AmpBiquad AMP_RESO_HIGH = ')
C.append('{ ' + ', '.join(f'{v:.9f}f' for v in reso_hi) + ' };\n\n')

# --- neve 1073-style: LF shelf 110 +1.5dB, mid 700 +1dB Q0.7, HF shelf 12k +1.5dB
#     Nashville: tight lows, subtle mid color, extra glass. ---
neve_lf = shelf(FS, 110.0, 1.5, False)
neve_mid = peaking(FS, 700.0, 0.7, 1.0)
neve_hf = shelf(FS, 12000.0, 1.5, True)
C.append('/* neve 1073-style tone (fixed brand color) */\n')
C.append('static const AmpBiquad AMP_NEVE[] = {\n')
C.append(fmt('lf shelf 110 +1.5dB', neve_lf)); C.append(fmt('mid 700 +1dB', neve_mid)); C.append(fmt('hf shelf 12k +1.5dB', neve_hf))
C.append('};\n#define AMP_NEVE_N 3\n\n')

# --- tone network runtime constants (Bass/Mid/Treble).
#     Fixed center frequencies; only the linear gain A changes at runtime,
#     so set_param needs just cos/sin/alpha constants + multiply-add. ---
def tone_consts(f0, q, high_shelf):
    w0 = 2.0 * np.pi * f0 / FS
    cos_w0 = np.cos(w0)
    sin_w0 = np.sin(w0)
    alpha = sin_w0 / (2.0 * q) if not high_shelf else sin_w0 * np.sqrt(2.0) / 2.0
    return cos_w0, sin_w0, alpha

cb, sb, ab = tone_consts(140.0, 0.9, False)    # bass: tight low control
cm, sm, am = tone_consts(850.0, 0.7, False)    # mid: forward presence (Nashville cut)
ct, st, at = tone_consts(5000.0, 0.8, False)   # treble: glass, no 3k honk
C.append('/* tone network runtime constants (linear gain A, no pow at runtime) */\n')
C.append(f'#define AMP_TONE_BASS_F0 140.0f\n')
C.append(f'#define AMP_TONE_BASS_COSW {cb:.9f}f\n')
C.append(f'#define AMP_TONE_BASS_SINW {sb:.9f}f\n')
C.append(f'#define AMP_TONE_BASS_ALPHA {ab:.9f}f\n')
C.append(f'#define AMP_TONE_MID_F0 850.0f\n')
C.append(f'#define AMP_TONE_MID_COSW {cm:.9f}f\n')
C.append(f'#define AMP_TONE_MID_SINW {sm:.9f}f\n')
C.append(f'#define AMP_TONE_MID_ALPHA {am:.9f}f\n')
C.append(f'#define AMP_TONE_TREB_F0 5000.0f\n')
C.append(f'#define AMP_TONE_TREB_COSW {ct:.9f}f\n')
C.append(f'#define AMP_TONE_TREB_SINW {st:.9f}f\n')
C.append(f'#define AMP_TONE_TREB_ALPHA {at:.9f}f\n')
C.append(f'#define AMP_TONE_TREB_HIGH 1\n\n')
C.append('#endif\n')

open(OUT, 'w', encoding='utf-8', newline='\n').write(''.join(C))
print('wrote', OUT)
