import numpy as np, os, sys
sys.stdout.reconfigure(encoding='utf-8')
FS = 44100.0
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', 'core', 'ampsim_coeffs.h'))

def peaking(fs, f0, q, gain_db):
    A = 10.0 ** (gain_db / 40.0)
    w0 = 2.0 * np.pi * f0 / fs
    alpha = np.sin(w0) / (2.0 * q)
    b0 = 1.0 + alpha * A; b1 = -2.0 * np.cos(w0); b2 = 1.0 - alpha * A
    a0 = 1.0 + alpha / A; a1 = -2.0 * np.cos(w0); a2 = 1.0 - alpha / A
    return np.array([b0/a0, b1/a0, b2/a0, a1/a0, a2/a0])

def shelf(fs, f0, gain_db, high):
    A = 10.0 ** (gain_db / 40.0)
    w0 = 2.0 * np.pi * f0 / fs
    alpha = np.sin(w0) * np.sqrt(2.0) / 2.0
    c = np.cos(w0); sA = 2.0 * np.sqrt(A) * alpha
    if not high:
        b0 = A * ((A+1.0) - (A-1.0)*c + sA); b1 = 2.0*A*((A-1.0) - (A+1.0)*c); b2 = A*((A+1.0) - (A-1.0)*c - sA)
        a0 = (A+1.0) + (A-1.0)*c + sA; a1 = -2.0*((A-1.0) + (A+1.0)*c); a2 = (A+1.0) + (A-1.0)*c - sA
    else:
        b0 = A * ((A+1.0) + (A-1.0)*c + sA); b1 = -2.0*A*((A-1.0) + (A+1.0)*c); b2 = A*((A+1.0) + (A-1.0)*c - sA)
        a0 = (A+1.0) - (A-1.0)*c + sA; a1 = 2.0*((A-1.0) - (A+1.0)*c); a2 = (A+1.0) - (A-1.0)*c - sA
    return np.array([b0/a0, b1/a0, b2/a0, a1/a0, a2/a0])

def butter(fs, fc, order, kind):
    from scipy import signal
    sos = signal.butter(order, fc, kind, fs=fs, output='sos')
    return [np.array([b0/a0, b1/a0, b2/a0, a1/a0, a2/a0]) for b0,b1,b2,a0,a1,a2 in sos]

def fmt(name, arr, indent='    '):
    s = ', '.join(f'{v:.9f}f' for v in arr)
    return f'{indent}/* {name} */ {{ {s} }},\n'

C = []
C.append('/* generated by tools/gen_coeffs.py - do not edit by hand. */\n')
C.append('#ifndef AMPNEVE_COEFFS_H\n#define AMPNEVE_COEFFS_H\n\n')
C.append('#define AMPNEVE_COEFFS_FS 44100.0f\n')
C.append('typedef struct { float b0, b1, b2, a1, a2; } AmpBiquad;\n\n')

hp90 = butter(FS, 90.0, 2, 'highpass')[0]
body = peaking(FS, 180.0, 1.0, 3.0)
pres_dark = peaking(FS, 3200.0, 1.2, 2.5)
lp_dark = butter(FS, 7000.0, 4, 'lowpass')
C.append('/* cab DARK chain (TONE=0) */\n')
C.append('static const AmpBiquad AMP_CAB_DARK[] = {\n')
C.append(fmt('hp90', hp90)); C.append(fmt('body180 +3dB', body)); C.append(fmt('pres3200 +2.5dB', pres_dark))
for i,b in enumerate(lp_dark): C.append(fmt(f'lp7000 4th #{i}', b))
C.append('};\n#define AMP_CAB_DARK_N 4\n\n')

pres_bright = peaking(FS, 3200.0, 1.2, 5.0)
lp_bright = butter(FS, 9000.0, 4, 'lowpass')
C.append('/* cab BRIGHT chain (TONE=1) */\n')
C.append('static const AmpBiquad AMP_CAB_BRIGHT[] = {\n')
C.append(fmt('hp90', hp90)); C.append(fmt('body180 +3dB', body)); C.append(fmt('pres3200 +5dB', pres_bright))
for i,b in enumerate(lp_bright): C.append(fmt(f'lp9000 4th #{i}', b))
C.append('};\n#define AMP_CAB_BRIGHT_N 4\n\n')

bass = peaking(FS, 180.0, 0.8, 4.0)
C.append('/* bass peaking */\n')
C.append('static const AmpBiquad AMP_BASS = ')
C.append('{ ' + ', '.join(f'{v:.9f}f' for v in bass) + ' };\n\n')

neve_lf = shelf(FS, 110.0, 2.5, False)
neve_mid = peaking(FS, 700.0, 0.7, 1.5)
neve_hf = shelf(FS, 12000.0, 1.0, True)
C.append('/* neve 1073-style tone */\n')
C.append('static const AmpBiquad AMP_NEVE[] = {\n')
C.append(fmt('lf shelf 110 +2.5dB', neve_lf)); C.append(fmt('mid 700 +1.5dB', neve_mid)); C.append(fmt('hf shelf 12k +1dB', neve_hf))
C.append('};\n#define AMP_NEVE_N 3\n\n')
C.append('#endif\n')

open(OUT, 'w', encoding='utf-8').write(''.join(C))
print('wrote', OUT, len(''.join(C)), 'bytes')
